### ISSUE TITLE
Error: Cannot find module '../hooks'

### ISSUE THREAD

**Issue by nilvon9wo** [yury-sannikov/mocha-aura#1]
Tried running the samples on my machine, but npm threw an error:

> auraSpecs@1.0.0 test D:\temp\mocha-aura\auraSpecs
> mocha  --require mocha-aura 'specs/**/*.js'

module.js:341
    throw err;
    ^

Error: Cannot find module '../hooks'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (D:\temp\mocha-aura\auraSpecs\node_modules\mocha-aura\dist\index.js:3:14)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:20:19)
    at D:\temp\mocha-aura\auraSpecs\node_modules\mocha\bin\_mocha:346:3
    at Array.forEach (native)
    at Object.<anonymous> (D:\temp\mocha-aura\auraSpecs\node_modules\mocha\bin\_mocha:345:10)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)
    at startup (node.js:148:18)
    at node.js:405:3
 npm ERR! Test failed.  See above for more details.

FWIW:

My environment consists of the following:
Windows XP SP3 (yes, I know...)
git version 2.10.0.windows.1
node version 5.12.0
npm version 4.2.0

Steps to reproduce:
git clone https://github.com/yury-sannikov/mocha-aura.git
cd mocha-aura/examples/salesforce/auraSpecs
npm install
npm install mocha-aura --save
npm test

**Comment by nilvon9wo** [comment]
I've tried:

1. npm install hooks
2. recursively, manually, installing hooks to each of the node_modules dependencies (a workaround suggested here: https://github.com/cliftonc/calipso/issues/42  )

... but neither of these resolved the issue.

**Comment by yury-sannikov** [comment]
Hey @nilvon9wo sorry for later reply. It should be already fixed in master.

**Comment by yury-sannikov** [comment]
gmail put all github updates as a spam =) fixed.
